version: '3.8'

services:
  agentic-agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: agentic-agent:latest
    env_file:
      - .env
    ports:
      - "5001:5001"
    restart: on-failure
